DROP TABLE IF EXISTS DELIVERS
CREATE TABLE DELIVERS (
	DELIVERY_ID INT,
	DELIVERY_PARTNER VARCHAR(50),
	PACKAGE_TYPE VARCHAR(50),
	VEHICLE_TYPE VARCHAR(60),
	DELIVERY_MODE VARCHAR(60),
	REGION VARCHAR(60),
	WEATHER_CONDITION VARCHAR(60),
	DISTANCE_KM NUMERIC(10, 2),
	PACKAGE_WEIGHT_KG NUMERIC(10, 2),
	DELIVERY_TIME_HOURS VARCHAR(40),
	EXPECTED_TIME_HOURS VARCHAR(40),
	DELAYED VARCHAR(60),
	DELIVERY_STATUS VARCHAR(60),
	DELIVERY_RATING NUMERIC(10, 2),
	DELIVERY_COST NUMERIC(10, 2)
);

-- 🟢 Beginner Level (10 Questions)
-- Q1 Count total deliveries.
SELECT
	COUNT(*)
FROM
	DELIVERS;

-- Q2 Count unique delivery partners. 
SELECT
	COUNT(DISTINCT DELIVERY_PARTNER)
FROM
	DELIVERS;

-- Q3 Show all distinct regions.
SELECT DISTINCT
	REGION
FROM
	DELIVERS;

-- Q4 Average delivery rating.
SELECT
	AVG(DELIVERY_RATING)
FROM
	DELIVERS;

-- Q5 Maximum delivery cost.
SELECT
	MAX(DELIVERY_COST) AS MAX_COST
FROM
	DELIVERS;

-- Q6 Minimum delivery time.
SELECT
	MIN(DELIVERY_TIME_HOURS)
FROM
	DELIVERS;

-- Q7 Count delayed deliveries.
SELECT
	COUNT(DELAYED) AS DELAYED_YES
FROM
	DELIVERS
WHERE
	DELAYED = 'Yes';

-- Q8 Count failed deliveries.
SELECT
	COUNT(*) AS FAILED_DELIVERYS
FROM
	DELIVERS
WHERE
	DELIVERY_STATUS = 'Failed';

-- Q9 Average package weight.
SELECT
	AVG(PACKAGE_WEIGHT_KG)
FROM
	DELIVERS;

-- Q10 Average distance.
SELECT
	AVG(DISTANCE_KM)
FROM
	DELIVERS;

-- 🟡 Intermediate Level (15 Questions)
-- Q11 Delay percentage.
SELECT
	ROUND(
		COUNT(
			CASE
				WHEN DELAYED = 'Yes' THEN 1
			END
		) * 100.0 / COUNT(DELAYED),
		2
	) AS DELAY_RATE
FROM
	DELIVERS
	-- Q12 Average cost by region.
SELECT
	AVG(DELIVERY_COST),
	REGION
FROM
	DELIVERS
GROUP BY
	REGION;

-- Q13 Average rating by delivery partner.
SELECT
	ROUND(AVG(DELIVERY_RATING), 2) AS AVG_RATING,
	DELIVERY_PARTNER
FROM
	DELIVERS
GROUP BY
	DELIVERY_PARTNER;

-- Q14 Top 5 most expensive deliveries.
SELECT
	DELIVERY_COST AS TOP_5_EXPENSIVE
FROM
	DELIVERS
ORDER BY
	DELIVERY_COST DESC
LIMIT
	5;

-- Q15 Total deliveries by package type.
SELECT
	COUNT(DELIVERY_ID),
	PACKAGE_TYPE
FROM
	DELIVERS
GROUP BY
	PACKAGE_TYPE;

-- Q16 Average delivery time by vehicle type.
SELECT
	AVG(DELIVERY_TIME_HOURS),
	VEHICLE_TYPE
FROM
	DELIVERS
GROUP BY
	VEHICLE_TYPE;

-- Q17 Delayed deliveries by weather condition. 
SELECT
	WEATHER_CONDITION,
	COUNT(DELAYED)
FROM
	DELIVERS
WHERE
	DELAYED = 'Yes'
GROUP BY
	WEATHER_CONDITION
	-- Q18 Failure rate by delivery partner.
SELECT
	ROUND(
		COUNT(
			CASE
				WHEN DELIVERY_STATUS = 'Failed' THEN 1
			END
		) * 100.0 / COUNT(DELIVERY_STATUS),
		2
	) AS FAILURE_RATE,
	DELIVERY_PARTNER
FROM
	DELIVERS
GROUP BY
	DELIVERY_PARTNER;
	-- Q19 Average cost by delivery mode.
SELECT
	AVG(DELIVERY_COST),
	DELIVERY_MODE
FROM
	DELIVERS
GROUP BY
	DELIVERY_MODE;
	-- Q20 Top 3 partners with highest ratings.
SELECT DISTINCT
	DELIVERY_PARTNER,
	DELIVERY_RATING
FROM
	DELIVERS
ORDER BY
	DELIVERY_RATING DESC
LIMIT;
	3;

-- Q21 Most used vehicle type.
SELECT
	COUNT(VEHICLE_TYPE),
	VEHICLE_TYPE
FROM
	DELIVERS
GROUP BY
	VEHICLE_TYPE
ORDER BY
	COUNT DESC
LIMIT
	1;

-- Q22 Region with highest delay rate.
SELECT
	REGION,
	ROUND(
		COUNT(
			CASE
				WHEN DELAYED = 'Yes' THEN 1
			END
		) * 100.0 / COUNT(DELAYED),
		2
	) AS DELAY_RATE
FROM
	DELIVERS
GROUP BY
	REGION
ORDER BY
	DELAY_RATE DESC;

-- Q23 Weather with lowest average rating.
SELECT DISTINCT
	WEATHER_CONDITION,
	ROUND(AVG(DELIVERY_RATING), 2) AS AVG_RATING
FROM
	DELIVERS
GROUP BY
	WEATHER_CONDITION
ORDER BY
	AVG_RATING ASC;

-- Q24 Average distance by package type.
SELECT
	AVG(DISTANCE_KM),
	PACKAGE_TYPE
FROM
	DELIVERS
GROUP BY
	PACKAGE_TYPE;

-- Q25 Average rating by weather.
SELECT
	AVG(DELIVERY_RATING),
	WEATHER_CONDITION
FROM
	DELIVERS
GROUP BY
	WEATHER_CONDITION;

-- ---
-- 🔴 Advanced Level (15 Questions)
-- Q26 Cost per kilometer.
SELECT
	DISTANCE_KM,
	DELIVERY_COST,
	ROUND(DELIVERY_COST / DISTANCE_KM, 2) AS PER_KM
FROM
	DELIVERS
	-- Q27 Compare actual vs expected time.
SELECT
	DELIVERY_TIME_HOURS,
	EXPECTED_TIME_HOURS
FROM
	DELIVERS
	-- Q28 Top 5 costly delayed deliveries.
SELECT
	DELAYED,
	DELIVERY_COST AS TOP_5_DLAY
FROM
	DELIVERS
WHERE
	DELAYED = 'Yes'
ORDER BY
	TOP_5_DLAY DESC
LIMIT
	5;

-- Q29 Delivery status distribution %.
SELECT
	ROUND(
		COUNT(
			CASE
				WHEN DELIVERY_STATUS = 'Failed' THEN 1
			END
		) * 100.0 / COUNT(DELIVERY_STATUS),
		2
	) AS FAILED,
	ROUND(
		COUNT(
			CASE
				WHEN DELIVERY_STATUS = 'Delivered' THEN 1
			END
		) * 100.0 / COUNT(DELIVERY_STATUS),
		2
	) AS DELIVERD
FROM
	DELIVERS;

-- Q30 Partner with highest failed deliveries.
SELECT
	DELIVERY_PARTNER,
	COUNT(DELIVERY_STATUS) FAIL_DELIVERS
FROM
	DELIVERS
WHERE
	DELIVERY_STATUS = 'Failed'
GROUP BY
	DELIVERY_PARTNER
ORDER BY
	FAIL_DELIVERS DESC
LIMIT
	1;

-- Q31 Average rating of delayed vs non-delayed.
SELECT
	DELIVERY_STATUS,
	ROUND(AVG(DELIVERY_RATING), 2)
FROM
	DELIVERS
GROUP BY
	DELIVERY_STATUS;

-- Q32 Most profitable delivery mode (highest avg cost).
SELECT
	DELIVERY_MODE,
	ROUND(AVG(DELIVERY_COST), 2) AS AVG_COST
FROM
	DELIVERS
GROUP BY
	DELIVERY_MODE
ORDER BY
	AVG_COST DESC
LIMIT
	1;

-- Q33 Weather impact on delay percentage.
SELECT
	WEATHER_CONDITION,
	ROUND(
		COUNT(
			CASE
				WHEN DELAYED = 'Yes' THEN 1
			END
		) * 100.0 / COUNT(DELAYED),
		2
	)
FROM
	DELIVERS
GROUP BY
	WEATHER_CONDITION;

-- Q34 Package type with highest cost per kg.
SELECT DISTINCT
	PACKAGE_TYPE,
	ROUND(AVG(DELIVERY_COST / PACKAGE_WEIGHT_KG), 2) AS COST_PER_KG
FROM
	DELIVERS
GROUP BY
	PACKAGE_TYPE
ORDER BY
	COST_PER_KG DESC
LIMIT
	1;

-- Q35 Vehicle type with fastest average delivery.
SELECT
	VEHICLE_TYPE,
	ROUND(AVG(DELIVERY_TIME_HOUR), 2) AS AVG_TIME
FROM
	DELIVERS
GROUP BY
	VEICLE_TYPE
ORDER BY
	AVG_TIME ASC
LIMIT
	1;

-- Q36 Rank partners by rating using RANK().
SELECT
	DELIVERY_PARTNER,
	ROUND(AVG(DELIVERY_RATING), 2) AS RATING,
	RANK() OVER (
		ORDER BY
			(DELIVERY_PARTNER) DESC
	)
FROM
	DELIVERS
GROUP BY
	DELIVERY_PARTNER
	-- Q37 Conditional CASE categorization for distance:
	-- Short (<50 km)
	-- Medium (50–150 km)
	-- Long (>150 km)
SELECT
	DISTANCE_KM,
	CASE
		WHEN DISTANCE_KM < 50 THEN 'Short'
		WHEN DISTANCE_KM BETWEEN 50 AND 150  THEN 'Medium'
		ELSE 'Long'
	END
FROM
	DELIVERS;

-- Q38 Delay percentage by distance category.
SELECT
	CASE
		WHEN DISTANCE_KM < 50 THEN 'Short'
		WHEN DISTANCE_KM BETWEEN 50 AND 150  THEN 'Medium'
		ELSE 'Long'
	END AS DISTANCE_CATG,
	ROUND(
		COUNT(
			CASE
				WHEN DELAYED = 'Yes' THEN 1
			END
		) * 100.0 / COUNT(DELAYED),
		2
	) AS DELAY_PERCENT
FROM
	DELIVERS
GROUP BY
	DISTANCE_KM;